[project]
name = "hello-python"
version = "0.1.0"
description = "An example Python application running in a container"
authors = [
    { name = "Mynth" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.52.3",
]

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "flake8>=7.3.0",
    "isort>=8.0.1",
    "black>=26.5.1",
    "pytest>=9.1.1",
]

[tool.poe.executor]
type = "uv"

[tool.poe.tasks]
dev = "uvicorn --host 0.0.0.0 --reload hello_python.app:app"
start = "uvicorn --host 0.0.0.0 hello_python.app:app"
format = "black ."

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
