name: CI

on:
  push:
    branches:
      - node
  pull_request:
    branches:
      - node

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check node/node-base.Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: node/node-base.Dockerfile

    - name: Check node/node-dev.Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: node/node-dev.Dockerfile

    - name: Check examples/node/Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: examples/node/Dockerfile

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wait-for-it

    - name: Build containers
      run: make

    - name: Run node-example container
      run: |
        docker run -d --name node-example -p 3000:3000 node-example

    - name: Wait for node-example container
      run: wait-for-it localhost:3000

    - name: Check node-example endpoint is working
      run: |
        for i in {1..10}; do curl http://localhost:3000/ && break || sleep 1; done

    - name: Stop node-example container
      run: docker stop node-example
