name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check python/python-base.Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: python/python-base.Dockerfile

    - name: Check python/python-dev.Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: python/python-dev.Dockerfile

    - name: Check examples/python/Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: examples/python/Dockerfile

    - name: Install wait-for-it
      run: |
        sudo apt-get update
        sudo apt-get install -y wait-for-it

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build python/python-base.Dockerfile
      uses: docker/build-push-action@v4
      with:
        file: python/python-base.Dockerfile
        context: python
        push: false
        load: true
        tags: quay.io/mynth/python-base:local

    - name: Build python/python-dev.Dockerfile
      uses: docker/build-push-action@v4
      with:
        file: python/python-dev.Dockerfile
        context: python
        push: false
        load: true
        tags: quay.io/mynth/python-dev:local

    - name: Build examples/python/Dockerfile
      uses: docker/build-push-action@v4
      with:
        context: examples/python
        push: false
        load: true
        tags: python-example

    - name: Build examples/python/Dockerfile
      run: |
        docker build -t python-example -f examples/python/Dockerfile examples/python

    - name: Run Docker container
      run: |
        docker run -d --name python-example -p 8000:8000 python-example

    - name: Wait for Docker container
      run: wait-for-it localhost:8000

    - name: Check endpoint is working
      run: |
        for i in {1..10}; do curl http://localhost:8000/ && break || sleep 1; done

    - name: Stop Docker container
      run: docker stop python-example
