name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check python/python-base.Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: python/python-base.Dockerfile

    - name: Check python/python-dev.Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: python/python-dev.Dockerfile

    - name: Check examples/python/Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: examples/python/Dockerfile

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wait-for-it

    - name: Build containers
      run: make

    - name: Run Docker container
      run: |
        docker run -d --name python-example -p 8000:8000 python-example

    - name: Wait for Docker container
      run: wait-for-it localhost:8000

    - name: Check endpoint is working
      run: |
        for i in {1..10}; do curl http://localhost:8000/ && break || sleep 1; done

    - name: Stop Docker container
      run: docker stop python-example
