name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check node-18/node-base.Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: node-18/node-base.Dockerfile

    - name: Check node-18/node-dev.Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: node-18/node-dev.Dockerfile

    - name: Check examples/node-18/Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: examples/node-18/Dockerfile

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wait-for-it

    - name: Build containers
      run: make node-18

    - name: Run node-18-example container
      run: |
        docker run -d --name node-18-example -p 3000:3000 node-18-example

    - name: Wait for node-18-example container
      run: wait-for-it localhost:3000

    - name: Check node-18-example endpoint is working
      run: |
        for i in {1..10}; do curl http://localhost:3000/ && break || sleep 1; done

    - name: Stop node-18-example container
      run: docker stop node-18-example
