name: Publish

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  publish-node-26:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Login to Quay.io
        uses: docker/login-action@v4.6.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ID }}
          password: ${{ secrets.QUAY_PW }}

      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Build node container
        run: |
          make build-node-26-base
          make build-node-26-dev

      - name: Publish container
        run: |
          TAG=$(git rev-parse --short HEAD)
          docker tag quay.io/mynth/node:26-base quay.io/mynth/node:26-base-$TAG
          docker tag quay.io/mynth/node:26-dev quay.io/mynth/node:26-dev-$TAG
          docker push quay.io/mynth/node:26-base
          docker push quay.io/mynth/node:26-dev
          docker push quay.io/mynth/node:26-base-$TAG
          docker push quay.io/mynth/node:26-dev-$TAG
        if: github.ref == 'refs/heads/main'

  publish-python:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Login to Quay.io
        uses: docker/login-action@v4.6.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ID }}
          password: ${{ secrets.QUAY_PW }}

      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Build python container
        run: |
          make build-python-base
          make build-python-dev

      - name: Publish container
        run: |
          TAG=$(git rev-parse --short HEAD)
          docker tag quay.io/mynth/python:base quay.io/mynth/python:base-$TAG
          docker tag quay.io/mynth/python:dev quay.io/mynth/python:dev-$TAG
          docker push quay.io/mynth/python:base
          docker push quay.io/mynth/python:dev
          docker push quay.io/mynth/python:base-$TAG
          docker push quay.io/mynth/python:dev-$TAG
        if: github.ref == 'refs/heads/main'

  publish-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Login to Quay.io
        uses: docker/login-action@v4.6.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ID }}
          password: ${{ secrets.QUAY_PW }}

      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Build worker container
        run: make build-worker

      - name: Publish container
        run: |
          TAG=$(git rev-parse --short HEAD)
          docker tag quay.io/mynth/worker:26 quay.io/mynth/worker:26-$TAG
          docker push quay.io/mynth/worker:26
          docker push quay.io/mynth/worker:26-$TAG
        if: github.ref == 'refs/heads/main'
