name: Tag Release

on:
  workflow_run:
    workflows:
      - CI
    branches:
      - python
    types:
      - completed

jobs:
  tag-release:
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Tag release
        run: |
          git tag -d TAG_NAME 2>/dev/null || true
          git tag python-release
          git push --force origin python-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
