name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-worker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.1

    - name: Check worker/worker.Dockerfile
      uses: hadolint/hadolint-action@v3.4.0
      with:
        dockerfile: worker/worker.Dockerfile

    - name: Check examples/worker/Dockerfile
      uses: hadolint/hadolint-action@v3.4.0
      with:
        dockerfile: examples/worker/Dockerfile

    - name: Build containers
      run: make worker

    - name: Run worker-example task
      run: |
        docker run --rm worker-example | tee worker-example.log
        grep -q "worker task completed" worker-example.log

    - name: Check worker tooling is available
      run: |
        docker run --rm quay.io/mynth/worker:dev node --version
        docker run --rm quay.io/mynth/worker:dev npm --version
        docker run --rm quay.io/mynth/worker:dev pnpm --version
        docker run --rm quay.io/mynth/worker:dev fnm --version
        docker run --rm quay.io/mynth/worker:dev fnm ls
        docker run --rm quay.io/mynth/worker:dev python --version
        docker run --rm quay.io/mynth/worker:dev uv --version
        docker run --rm quay.io/mynth/worker:dev uvx --version
        docker run --rm quay.io/mynth/worker:dev poe --version

    - name: Check worker user can modify its environment
      run: |
        docker run --rm quay.io/mynth/worker:dev sudo -n whoami
        docker run --rm quay.io/mynth/worker:dev sh -c 'sudo -n apt-get update -qq && sudo -n apt-get install -y --no-install-recommends jq && jq --version'
